#!/usr/bin/env bash

git submodule update --init --recursive

OS=`curl -L https://raw.githubusercontent.com/wxnacy/wshell/master/bin/base/os | bash`
OSS=(${OS})
SYS=${OSS[0]}
VER=${OSS[1]}

case $SYS in
    debian|ubuntu|devuan)
        sudo apt update -y
        sudo apt install -y ack-grep
        ;;
    centos|fedora|rhel|amzn)
        sudo yum update -y
        sudo yum -y install epel-release ack
        ;;
    Darwin)
        brew install ack
        ;;
    *)
        echo '暂时不支持该系统'
        ;;
esac
