#!/usr/bin/env bash

git submodule update --init --recursive

OS=`curl -L https://raw.githubusercontent.com/wxnacy/wshell/master/bin/base/os | bash`
OSS=(${OS})
SYS=${OSS[0]}
VER=${OSS[1]}



if [ $SYS == 'ubuntu' ];then
    sudo apt update -y
    sudo apt install -y ack-grep
fi

if [ $SYS == 'centos' ];then
    sudo yum update -y
    sudo yum -y install epel-release ack
fi
